# Generated by Django 4.2.17 on 2024-12-27 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='models.matchday'),
        ),
        migrations.AddField(
            model_name='player',
            name='match_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matchday', to='models.matchday'),
        ),
        migrations.AlterField(
            model_name='player',
            name='cannot_play',
            field=models.CharField(choices=[('w', 'white'), ('r', 'red'), ('g', 'green'), ('u', 'blue'), ('b', 'black')], default='w', max_length=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='has_to_play',
            field=models.CharField(choices=[('w', 'white'), ('r', 'red'), ('g', 'green'), ('u', 'blue'), ('b', 'black')], default='w', max_length=1),
        ),
    ]
