# Generated by Django 4.2.17 on 2024-12-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_match_match_day_player_match_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='cannot_play',
            field=models.CharField(choices=[('w', 'white'), ('b', 'black'), ('u', 'blue'), ('r', 'red'), ('g', 'green')], default='w', max_length=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='has_to_play',
            field=models.CharField(choices=[('w', 'white'), ('b', 'black'), ('u', 'blue'), ('r', 'red'), ('g', 'green')], default='w', max_length=1),
        ),
    ]
