# Generated by Django 4.2.17 on 2024-12-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_alter_player_cannot_play_alter_player_has_to_play'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchday',
            name='set',
        ),
        migrations.AddField(
            model_name='matchday',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchday',
            name='match_type',
            field=models.CharField(choices=[('bo3', 'Best of 3'), ('bo1', 'Best of 1'), ('bo5', 'Best of 5'), ('bo2', 'Best of 2')], default='bo2', max_length=3),
        ),
        migrations.AddField(
            model_name='matchday',
            name='set_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='cannot_play',
            field=models.CharField(choices=[('g', 'green'), ('u', 'blue'), ('b', 'black'), ('w', 'white'), ('r', 'red')], default='w', max_length=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='has_to_play',
            field=models.CharField(choices=[('g', 'green'), ('u', 'blue'), ('b', 'black'), ('w', 'white'), ('r', 'red')], default='w', max_length=1),
        ),
    ]
