# Generated by Django 4.2.17 on 2024-12-28 12:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_remove_matchday_set_matchday_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='scores',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='matchday',
            name='match_type',
            field=models.CharField(choices=[('bo3', 'Best of 3'), ('bo2', 'Best of 2'), ('bo1', 'Best of 1'), ('bo5', 'Best of 5')], default='bo2', max_length=3),
        ),
        migrations.AlterField(
            model_name='player',
            name='cannot_play',
            field=models.CharField(choices=[('w', 'white'), ('b', 'black'), ('u', 'blue'), ('g', 'green'), ('r', 'red')], default='w', max_length=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='has_to_play',
            field=models.CharField(choices=[('w', 'white'), ('b', 'black'), ('u', 'blue'), ('g', 'green'), ('r', 'red')], default='w', max_length=1),
        ),
    ]
