# Generated by Django 4.2.17 on 2025-01-03 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_alter_match_scores_alter_matchday_match_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('display_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='person',
        ),
        migrations.AlterField(
            model_name='matchday',
            name='match_type',
            field=models.CharField(choices=[('bo3', 'Best of 3'), ('bo1', 'Best of 1'), ('bo5', 'Best of 5'), ('bo2', 'Best of 2')], default='bo2', max_length=3),
        ),
        migrations.AlterField(
            model_name='player',
            name='cannot_play',
            field=models.CharField(choices=[('w', 'white'), ('b', 'black'), ('r', 'red'), ('g', 'green'), ('u', 'blue')], default='w', max_length=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='has_to_play',
            field=models.CharField(choices=[('w', 'white'), ('b', 'black'), ('r', 'red'), ('g', 'green'), ('u', 'blue')], default='w', max_length=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='match_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='models.matchday'),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='player',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='models.member'),
        ),
    ]
