# Generated by Django 4.2.17 on 2025-01-10 18:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_member_remove_player_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='has_to_play',
        ),
        migrations.AddField(
            model_name='player',
            name='must_play',
            field=models.CharField(choices=[('w', 'white'), ('u', 'blue'), ('r', 'red'), ('b', 'black'), ('g', 'green')], default='w', max_length=1),
        ),
        migrations.AddField(
            model_name='player',
            name='plays',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1), blank=True, default=list, size=5),
        ),
        migrations.AlterField(
            model_name='matchday',
            name='match_type',
            field=models.CharField(choices=[('bo2', 'Best of 2'), ('bo5', 'Best of 5'), ('bo3', 'Best of 3'), ('bo1', 'Best of 1')], default='bo2', max_length=3),
        ),
        migrations.AlterField(
            model_name='player',
            name='cannot_play',
            field=models.CharField(choices=[('w', 'white'), ('u', 'blue'), ('r', 'red'), ('b', 'black'), ('g', 'green')], default='w', max_length=1),
        ),
    ]
