# Generated by Django 4.2.17 on 2025-01-10 18:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_remove_player_has_to_play_player_must_play_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchday',
            name='match_type',
            field=models.CharField(choices=[('bo3', 'Best of 3'), ('bo5', 'Best of 5'), ('bo1', 'Best of 1'), ('bo2', 'Best of 2')], default='bo2', max_length=3),
        ),
        migrations.AlterField(
            model_name='player',
            name='cannot_play',
            field=models.CharField(choices=[('b', 'black'), ('g', 'green'), ('r', 'red'), ('u', 'blue'), ('w', 'white')], default='w', max_length=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='must_play',
            field=models.CharField(choices=[('b', 'black'), ('g', 'green'), ('r', 'red'), ('u', 'blue'), ('w', 'white')], default='w', max_length=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='plays',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('b', 'black'), ('g', 'green'), ('r', 'red'), ('u', 'blue'), ('w', 'white')], default='w', max_length=1), blank=True, default=list, size=5),
        ),
    ]
