# Generated by Django 4.2.17 on 2025-01-10 18:49

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_alter_matchday_match_type_alter_player_cannot_play_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='cannot_play',
            field=models.CharField(choices=[('b', 'black'), ('u', 'blue'), ('r', 'red'), ('w', 'white'), ('g', 'green')], default='w', max_length=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='match_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matchday', to='models.matchday'),
        ),
        migrations.AlterField(
            model_name='player',
            name='must_play',
            field=models.CharField(choices=[('b', 'black'), ('u', 'blue'), ('r', 'red'), ('w', 'white'), ('g', 'green')], default='w', max_length=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='plays',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('b', 'black'), ('u', 'blue'), ('r', 'red'), ('w', 'white'), ('g', 'green')], default='w', max_length=1), blank=True, default=list, size=5),
        ),
    ]
