# Generated by Django 4.2.17 on 2025-01-10 18:59

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_rename_match_day_player_matchday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchday',
            name='match_type',
            field=models.CharField(choices=[('bo1', 'Best of 1'), ('bo5', 'Best of 5'), ('bo3', 'Best of 3'), ('bo2', 'Best of 2')], default='bo2', max_length=3),
        ),
        migrations.AlterField(
            model_name='player',
            name='cannot_play',
            field=models.CharField(choices=[('g', 'green'), ('u', 'blue'), ('b', 'black'), ('r', 'red'), ('w', 'white')], default='w', max_length=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='matchday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='models.matchday'),
        ),
        migrations.AlterField(
            model_name='player',
            name='must_play',
            field=models.CharField(choices=[('g', 'green'), ('u', 'blue'), ('b', 'black'), ('r', 'red'), ('w', 'white')], default='w', max_length=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='plays',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('g', 'green'), ('u', 'blue'), ('b', 'black'), ('r', 'red'), ('w', 'white')], default='w', max_length=1), blank=True, default=list, size=5),
        ),
    ]
