# Generated by Django 4.2.17 on 2025-01-10 21:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0012_alter_matchday_match_type_alter_matchday_set_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchday',
            name='is_included',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='matchday',
            name='match_type',
            field=models.CharField(choices=[('bo5', 'Best of 5'), ('bo2', 'Best of 2'), ('bo1', 'Best of 1'), ('bo3', 'Best of 3')], default='bo2', max_length=3),
        ),
        migrations.AlterField(
            model_name='player',
            name='cannot_play',
            field=models.CharField(choices=[('u', 'blue'), ('w', 'white'), ('b', 'black'), ('r', 'red'), ('g', 'green')], default='w', max_length=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='must_play',
            field=models.CharField(choices=[('u', 'blue'), ('w', 'white'), ('b', 'black'), ('r', 'red'), ('g', 'green')], default='w', max_length=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='plays',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('u', 'blue'), ('w', 'white'), ('b', 'black'), ('r', 'red'), ('g', 'green')], default='w', max_length=1), blank=True, default=list, size=5),
        ),
    ]
