# Generated by Django 4.2.17 on 2025-01-11 14:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0013_matchday_is_included_alter_matchday_match_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='scores',
        ),
        migrations.AddField(
            model_name='match',
            name='score_player_one',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='score_player_two',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matchday',
            name='match_type',
            field=models.CharField(choices=[('bo3', 'Best of 3'), ('bo1', 'Best of 1'), ('bo2', 'Best of 2'), ('bo5', 'Best of 5')], default='bo2', max_length=3),
        ),
        migrations.AlterField(
            model_name='player',
            name='cannot_play',
            field=models.CharField(choices=[('r', 'red'), ('u', 'blue'), ('b', 'black'), ('w', 'white'), ('g', 'green')], default='w', max_length=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='must_play',
            field=models.CharField(choices=[('r', 'red'), ('u', 'blue'), ('b', 'black'), ('w', 'white'), ('g', 'green')], default='w', max_length=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='plays',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('r', 'red'), ('u', 'blue'), ('b', 'black'), ('w', 'white'), ('g', 'green')], default='w', max_length=1), blank=True, default=list, size=5),
        ),
    ]
