# Generated by Django 4.2.17 on 2025-01-28 20:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0016_alter_matchday_match_type_alter_player_cannot_play_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchday',
            name='match_type',
            field=models.CharField(choices=[('bo5', 'Best of 5'), ('bo2', 'Best of 2'), ('bo3', 'Best of 3'), ('bo1', 'Best of 1')], default='bo2', max_length=3),
        ),
        migrations.AlterField(
            model_name='player',
            name='cannot_play',
            field=models.CharField(choices=[('w', 'white'), ('g', 'green'), ('b', 'black'), ('r', 'red'), ('u', 'blue')], default='w', max_length=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='must_play',
            field=models.CharField(choices=[('w', 'white'), ('g', 'green'), ('b', 'black'), ('r', 'red'), ('u', 'blue')], default='w', max_length=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='plays',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('w', 'white'), ('g', 'green'), ('b', 'black'), ('r', 'red'), ('u', 'blue')], default='w', max_length=1), blank=True, default=list, size=5),
        ),
    ]
