# # Use the official Node.js image from Docker Hub
# FROM node:18

# # Set the working directory inside the container
# WORKDIR /app

# # Copy the package.json and package-lock.json (if available) into the container
# COPY ./frontend/package.json ./frontend/package-lock.json /app/

# # Install the dependencies
# RUN npm install

# # Copy the rest of the application code into the container
# COPY ./frontend/ /app/

# # Expose the port React will run on
# EXPOSE 3000

# # Command to start React development server
# CMD ["npm", "start"]

# Dockerfile for React (Vite)



# Use Node.js as the base image
# FROM node:18-alpine

# # Set working directory in the container
# WORKDIR /app

# # Copy package.json and package-lock.json
# COPY package*.json ./

# # Install dependencies
# RUN npm install

# # Copy the rest of the app
# COPY . .

# # Build the app
# RUN npm run build

# # Serve the app using a lightweight HTTP server
# # RUN npm install -g serve
# # CMD ["serve", "-s", "dist", "-l", "3000"]

# CMD ["npm", "start"]

# # Expose port 3000
# EXPOSE 3000



# Use the official Node.js image from Docker Hub
FROM node:18

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json (if available) into the container
COPY ./frontend/package.json ./frontend/package-lock.json /app/

# Install the dependencies
RUN npm install

# Copy the rest of the application code into the container
COPY ./frontend/ /app/

# Expose the port React will run on
EXPOSE 3000

# Command to start React development server
CMD ["npm", "start"]