# version: "3.8"
services:
  db:
    image: postgres:13
    container_name: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      # - "POSTGRES_HOST_AUTH_METHOD=trust"
      POSTGRES_DB: mtgdatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  backend:
    volumes:
      - ./backend:/app
    build:
      context: .
      dockerfile: ./backend/Dockerfile.backend
    container_name: django
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://myuser:postgres@db:5432/mtgdatabase

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: ./frontend/Dockerfile.frontend
  #   container_name: react
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - REACT_APP_API_URL=http://localhost:8000/api
  #   depends_on:
  #     - backend

volumes:
  postgres_data: